### ISSUE TITLE
exclamation point in hostname

### ISSUE THREAD

**Issue by nadavoosh** [tokyo-jesus/validate-email-address#6]
```
>>> from validate_email_address import validate_email
>>> validate_email('asdf@!df.com')
True
```

This should return `False`

**Comment by tokyo-jesus** [comment]
That is a valid email address according to RFC 2822. See sections [3.2.4] and [3.4.1]. If you want to validate that you are seeing a deliverable email address, you should enable MX or SMTP server checking.

[3.2.4]: https://tools.ietf.org/html/rfc2822#section-3.2.4
[3.4.1]: https://tools.ietf.org/html/rfc2822#section-3.4.1
